#ifndef QTMVVMSETTINGSCORE_GLOBAL_H
#define QTMVVMSETTINGSCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT_BUILD_MVVMSETTINGSCORE_LIB)
#  define Q_MVVMSETTINGSCORE_EXPORT Q_DECL_EXPORT
#else
#  define Q_MVVMSETTINGSCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // QTMVVMSETTINGSCORE_GLOBAL_H
