#ifndef QTMVVMDATASYNCCORE_GLOBAL_H
#define QTMVVMDATASYNCCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef QT_STATIC
#  if defined(QT_BUILD_MVVMDATASYNCCORE_LIB)
#    define Q_MVVMDATASYNCCORE_EXPORT Q_DECL_EXPORT
#  else
#    define Q_MVVMDATASYNCCORE_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_MVVMDATASYNCCORE_EXPORT
#endif

#endif // QTMVVMDATASYNCCORE_GLOBAL_H
