var searchData=
[
  ['dataexchangeport',['DataExchangePort',['https://skycoder42.github.io/QtDataSync/class_qt_data_sync_1_1_user_exchange_manager.html#aca533e63172f0a8528a9fe3b7d17995b',0,'QtDataSync::UserExchangeManager']]],
  ['datasizeformats',['DataSizeFormats',['https://doc.qt.io/qt-5/qlocale.html#DataSizeFormat-enum',0,'QLocale']]],
  ['decoderfn',['DecoderFn',['https://doc.qt.io/qt-5/qfile.html#DecoderFn-typedef',0,'QFile']]],
  ['defaultoldstoragedir',['DefaultOldStorageDir',['https://skycoder42.github.io/QtDataSync/class_qt_data_sync_1_1_migration_helper.html#a58371c88d3d6bf41aa7d89b522aac15b',0,'QtDataSync::MigrationHelper']]],
  ['defaultsetup',['DefaultSetup',['https://skycoder42.github.io/QtDataSync/namespace_qt_data_sync.html#abb171604c163b92d50237e784d6b7631',0,'QtDataSync']]],
  ['defaultvalue',['defaultValue',['../namespace_qt_mvvm_1_1_settings_elements.html#a89286adcd6f467550c78690467992485',1,'QtMvvm::SettingsElements::Entry']]],
  ['deleteverb',['DeleteVerb',['https://doc.qt.io/qt-5/class_qt_rest_client_1_1_rest_class.html#aac3ffebd561e942f2aac0a669101fb5f',0,'QtRestClient::RestClass']]],
  ['deliveryflags',['DeliveryFlags',['https://doc.qt.io/qt-5/qt3dcore-qscenechange.html#DeliveryFlag-enum',0,'Qt3DCore::QSceneChange']]],
  ['deserializationerror',['DeserializationError',['https://doc.qt.io/qt-5/class_qt_rest_client_1_1_rest_reply.html#a7ac2c77cd405dff6fd116eaf3073fe2aa9a0c862f9ee36946a59f22c092970832',0,'QtRestClient::RestReply']]],
  ['difference_5ftype',['difference_type',['https://doc.qt.io/qt-5/qstringview.html#difference_type-typedef',0,'QStringView::difference_type()'],['https://doc.qt.io/qt-5/qlatin1string.html#difference_type-typedef',0,'QLatin1String::difference_type()'],['https://doc.qt.io/qt-5/qstring.html#difference_type-typedef',0,'QString::difference_type()'],['https://doc.qt.io/qt-5/qlist.html#difference_type-typedef',0,'QList::difference_type()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#difference_type-typedef',0,'QVarLengthArray::difference_type()'],['https://doc.qt.io/qt-5/qmap.html#difference_type-typedef',0,'QMap::difference_type()'],['https://doc.qt.io/qt-5/qhash.html#difference_type-typedef',0,'QHash::difference_type()'],['https://doc.qt.io/qt-5/qvector.html#difference_type-typedef',0,'QVector::difference_type()'],['https://doc.qt.io/qt-5/qset.html#difference_type-typedef',0,'QSet::difference_type()'],['https://doc.qt.io/qt-5/qset-iterator.html#difference_type-typedef',0,'QSet::iterator::difference_type()'],['https://doc.qt.io/qt-5/qset-const-iterator.html#difference_type-typedef',0,'QSet::const_iterator::difference_type()'],['https://doc.qt.io/qt-5/qfuture-const-iterator.html#difference_type-typedef',0,'QFuture::const_iterator::difference_type()'],['https://doc.qt.io/qt-5/qjsonarray.html#difference_type-typedef',0,'QJsonArray::difference_type()'],['https://doc.qt.io/qt-5/qlinkedlist.html#difference_type-typedef',0,'QLinkedList::difference_type()']]],
  ['dirtyflags',['DirtyFlags',['https://doc.qt.io/qt-5/qpaintengine.html#DirtyFlag-enum',0,'QPaintEngine']]],
  ['dirtystate',['DirtyState',['https://doc.qt.io/qt-5/qsgnode.html#DirtyStateBit-enum',0,'QSGNode']]],
  ['dirtystates',['DirtyStates',['https://doc.qt.io/qt-5/qsgmaterialshader-renderstate.html#DirtyState-enum',0,'QSGMaterialShader::RenderState']]],
  ['disabled',['Disabled',['https://skycoder42.github.io/QtJsonSerializer/class_q_json_serializer.html#aaf1235d174ee19e269d85a9a0d909e72a22919891b604cb7b35cfe91a463f5864',0,'QJsonSerializer']]],
  ['disconnected',['Disconnected',['https://skycoder42.github.io/QtDataSync/class_qt_data_sync_1_1_sync_manager.html#a88370b2fba5ecb3602d60e08b0a66699a9fbf10c4826679abe58e857bddaed115',0,'QtDataSync::SyncManager']]],
  ['discoverymethods',['DiscoveryMethods',['https://doc.qt.io/qt-5/qbluetoothdevicediscoveryagent.html#DiscoveryMethod-enum',0,'QBluetoothDeviceDiscoveryAgent']]],
  ['dockoptions',['DockOptions',['https://doc.qt.io/qt-5/qmainwindow.html#DockOption-enum',0,'QMainWindow']]],
  ['dockwidgetareas',['DockWidgetAreas',['https://doc.qt.io/qt-5/qt.html#DockWidgetArea-enum',0,'Qt']]],
  ['dockwidgetfeatures',['DockWidgetFeatures',['https://doc.qt.io/qt-5/qdockwidget.html#DockWidgetFeature-enum',0,'QDockWidget']]],
  ['downloading',['Downloading',['https://skycoder42.github.io/QtDataSync/class_qt_data_sync_1_1_sync_manager.html#a88370b2fba5ecb3602d60e08b0a66699a7309df3683c803709c5f8d3b4526111f',0,'QtDataSync::SyncManager']]],
  ['dropactions',['DropActions',['https://doc.qt.io/qt-5/qt.html#DropAction-enum',0,'Qt']]]
];
