var searchData=
[
  ['rangeaccessflags',['RangeAccessFlags',['https://doc.qt.io/qt-5/qopenglbuffer.html#RangeAccessFlag-enum',0,'QOpenGLBuffer']]],
  ['rawheader',['RawHeader',['https://doc.qt.io/qt-5/qnetworkcachemetadata.html#RawHeader-typedef',0,'QNetworkCacheMetaData']]],
  ['rawheaderlist',['RawHeaderList',['https://doc.qt.io/qt-5/qnetworkcachemetadata.html#RawHeaderList-typedef',0,'QNetworkCacheMetaData']]],
  ['rawheaderpair',['RawHeaderPair',['https://doc.qt.io/qt-5/qnetworkreply.html#RawHeaderPair-typedef',0,'QNetworkReply']]],
  ['readfunc',['ReadFunc',['https://doc.qt.io/qt-5/qsettings.html#ReadFunc-typedef',0,'QSettings']]],
  ['reduceoptions',['ReduceOptions',['https://doc.qt.io/qt-5/qtconcurrent.html#ReduceOption-enum',0,'QtConcurrent']]],
  ['reference',['reference',['https://doc.qt.io/qt-5/qjsonarray.html#reference-typedef',0,'QJsonArray::reference()'],['https://doc.qt.io/qt-5/qfuture-const-iterator.html#reference-typedef',0,'QFuture::const_iterator::reference()'],['https://doc.qt.io/qt-5/qlinkedlist.html#reference-typedef',0,'QLinkedList::reference()'],['https://doc.qt.io/qt-5/qlist.html#reference-typedef',0,'QList::reference()'],['https://doc.qt.io/qt-5/qset.html#reference-typedef',0,'QSet::reference()'],['https://doc.qt.io/qt-5/qstring.html#reference-typedef',0,'QString::reference()'],['https://doc.qt.io/qt-5/qstringview.html#reference-typedef',0,'QStringView::reference()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#reference-typedef',0,'QVarLengthArray::reference()'],['https://doc.qt.io/qt-5/qvector.html#reference-typedef',0,'QVector::reference()']]],
  ['regexpmode',['RegexpMode',['https://skycoder42.github.io/QtDataSync/class_qt_data_sync_1_1_data_store.html#aeab660dbab47360b7ba4f7f87620778fae37ab7cefd4c486319a4d8549bc15cb1',0,'QtDataSync::DataStore']]],
  ['relation',['Relation',['https://doc.qt.io/qt-5/qaccessible.html#RelationFlag-enum',0,'QAccessible']]],
  ['remoteconfiguration',['RemoteConfiguration',['https://skycoder42.github.io/QtDataSync/class_qt_data_sync_1_1_defaults.html#ab141dc12df2cd9395e3e5b1fc31c1c39a3049ae8f050bb7996701672046a240f1',0,'QtDataSync::Defaults']]],
  ['renderflags',['RenderFlags',['https://doc.qt.io/qt-5/qwidget.html#RenderFlag-enum',0,'QWidget::RenderFlags()'],['https://doc.qt.io/qt-5/qtextitem.html#RenderFlag-enum',0,'QTextItem::RenderFlags()']]],
  ['renderhints',['RenderHints',['https://doc.qt.io/qt-5/qpainter.html#RenderHint-enum',0,'QPainter']]],
  ['renderingflags',['RenderingFlags',['https://doc.qt.io/qt-5/qsgrendernode.html#RenderingFlag-enum',0,'QSGRenderNode']]],
  ['result',['Result',['https://doc.qt.io/qt-5/qgesturerecognizer.html#ResultFlag-enum',0,'QGestureRecognizer']]],
  ['result_5ftype',['result_type',['https://doc.qt.io/qt-5/qrandomgenerator64.html#result_type-typedef',0,'QRandomGenerator64']]],
  ['reverse_5fiterator',['reverse_iterator',['https://doc.qt.io/qt-5/qbytearray.html#reverse_iterator-typedef',0,'QByteArray::reverse_iterator()'],['https://doc.qt.io/qt-5/qlinkedlist.html#reverse_iterator-typedef',0,'QLinkedList::reverse_iterator()'],['https://doc.qt.io/qt-5/qlist.html#reverse_iterator-typedef',0,'QList::reverse_iterator()'],['https://doc.qt.io/qt-5/qset.html#reverse_iterator-typedef',0,'QSet::reverse_iterator()'],['https://doc.qt.io/qt-5/qstring.html#reverse_iterator-typedef',0,'QString::reverse_iterator()'],['https://doc.qt.io/qt-5/qstringview.html#reverse_iterator-typedef',0,'QStringView::reverse_iterator()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#reverse_iterator-typedef',0,'QVarLengthArray::reverse_iterator()'],['https://doc.qt.io/qt-5/qvector.html#reverse_iterator-typedef',0,'QVector::reverse_iterator()']]],
  ['routeoptimizations',['RouteOptimizations',['https://doc.qt.io/qt-5/qgeorouterequest.html#RouteOptimization-enum',0,'QGeoRouteRequest']]],
  ['routingfeatures',['RoutingFeatures',['https://doc.qt.io/qt-5/qgeoserviceprovider.html#RoutingFeature-enum',0,'QGeoServiceProvider']]],
  ['rsa_5foaep_5fsha3_5f512',['RSA_OAEP_SHA3_512',['https://skycoder42.github.io/QtDataSync/class_qt_data_sync_1_1_setup.html#acd5b9c5d0b0fccdefe0bf3efba02736ca28ed05fa84cfceba71b37aa062ab2859',0,'QtDataSync::Setup']]],
  ['rsa_5fpss_5fsha3_5f512',['RSA_PSS_SHA3_512',['https://skycoder42.github.io/QtDataSync/class_qt_data_sync_1_1_setup.html#a2782b8dd5c9732b91126ff16aa49d460aa2975cb44355bcbd403ae5e3a0f23c96',0,'QtDataSync::Setup']]]
];
