#ifndef QTMVVMSETTINGSWIDGETS_GLOBAL_H
#define QTMVVMSETTINGSWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT_BUILD_MVVMSETTINGSWIDGETS_LIB)
#  define Q_MVVMSETTINGSWIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define Q_MVVMSETTINGSWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // QTMVVMSETTINGSWIDGETS_GLOBAL_H
